blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""определяет схемы url for blogs"""

from django.urls import path, include

from . import views

app_name = 'blogs'

urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # page to add new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for edit blogs
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    # page for list of blogs
    path('blogs/', views.blogs, name='blogs'),
]

users/urls.py
"""определяет схемы URL для пользователей"""  

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # включить URL афторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    # cтраница регистрации
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
	"""создает блог"""
	title = models.CharField(max_length=100)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""возврвщает строковое представление модели"""
		return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'title': 'Title', 'text': 'Enter text'}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogForm

def  index(request):
	"""home page of blogs app, выводит список тем"""
	#blogs = BlogPost.objects.order_by('date_added')
	#context = {'blogs': blogs}
	#return render(request, 'blogs/index.html', context)
	return render(request, 'blogs/index.html')

@login_required
def  blogs(request):
	"""home page of blogs app, выводит список тем"""
	blogs = BlogPost.objects.filter(owner=request.user).order_by('date_added')
	context = {'blogs': blogs}
	return render(request, 'blogs/blogs.html', context)

@login_required
def new_blog(request):
	"""определяет новый блог"""
	if request.method != 'POST':
		# данные не отправлялись; создается пустая форма
		form = BlogForm()	
	else:
		# Отправлены данные ПОСТ; обработать данные
		form = BlogForm(data=request.POST)
		if form.is_valid():
			new_blog = form.save(commit=False)
			new_blog.owner = request.user
			new_blog.save()
			return redirect('blogs:blogs') # перенаправляет на страницу index

	# вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'blogs/new_blog.html', context)

@login_required
def edit_blog(request, blog_id):
	"""редактирует существующий блог"""
	
	blog = BlogPost.objects.get(id=blog_id)
	if blog.owner != request.user:
		return render(request, 'blogs/index.html') # отправляет на страницу index
		# raise Http404

	if request.method != 'POST':
		# Исходный запрос: форма заполняется данными текущей записи
		form = BlogForm(instance=blog)
		
	else:
		# Отправлены данные ПОСТ; обработать данные
		form = BlogForm(instance=blog, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blogs:blogs')

	context = {'blog': blog, 'form': form}
	return render(request, 'blogs/edit.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""регистрирует нового пользователя"""
	if request.method !='POST':
		# выводит пустую форму регистрации
		form = UserCreationForm()
	else:
		# Обработка заполненной формы
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# выполнение входа и перенаправление на домашнюю страницу
			login(request, new_user)
			return redirect('blogs:index')

	# вывести пустую или не действительную форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>My Blog</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'blogs:index'%}">
        Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:blogs'%}">
              My Blogs</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h3>My blogs:</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'blogs:new_blog' %}">Add new blog</a>
  </p>

  <ul>
  {% for blog in blogs %}
    <div class="card mb-3">
      <h4 class="card-header">
  	  {{ blog.title }}
        <p>{{ blog.date_added|date:'M d, Y H:i' }}</p>
        <small><a href="{% url 'blogs:edit_blog' blog.id %}">
            edit blog</a></small>
      </h4>
      <div class="card-body">
        {{ blog.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>You have no blogs.</p>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/edit.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>Edit blog:</p>
{% endblock page_header %}

{% block content %}
    
  <form method='post' action="{% url 'blogs:edit_blog' blog.id %}" class="form" >
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
    
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class="jumbotron">

    {% if user.is_authenticated %}
      <h3 class="display-4">Hello, {{ user.username }} .Lets start Blogs.</h3>
      <a href="{% url 'blogs:new_blog' %}">Add a new blog:</a>
    {% else %}
    <p><h3>Whats up User! Do you wanna register?</h2></p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>Add a new blog:</p>
{% endblock page_header %}

{% block content %}
    
  <form method='post' action="{% url 'blogs:new_blog' %}" class="form" >
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add blog</button>
    {% endbuttons %}
  </form>
    
{% endblock content %}